---
title: "Top 100 Books - Analysis"
author: "Juliana Sophia Pabonita"
output: html_document
---

```{r message = FALSE, warning = FALSE}
# load packages
library(dplyr)
library(readr)
library(ggplot2)
```

```{r}
# read csv files
books <- read_csv("top_100_books.csv")

# intial inspection of the data frame
glimpse(books)
head(books)
```

```{r}
# basic summaries
summary(books)
mean(books$Ages, na.rm = TRUE)
sd(books$Ages, na.rm = TRUE)
range(books$Year)

# rename first column (optional)
books <- books %>%
  rename(Rank = "...1")

# check if max year can be examined & find year with most books publlished
table(duplicated(books$Year))

yr <- books %>%
  group_by(Year) %>%
  summarize(count = n()) %>%
  filter(count == max(count))
yr

# identify which books these are (optional)
bk <- books %>%
  group_by(Year, 
           Author, 
           Title) %>%
  filter(Year == 1925 |
         Year == 1967) %>%
  arrange(Year)
bk

# identify at what age on average these books were published
bk_age <- bk %>%
  summarize(mean(Ages), na.rm = TRUE)
print(paste("The top 100 books were published at age", format(top_20_avg_age, digits = 2), "on average."))

# identify at what age the top 20 books were published (addtl)
bk_top_20 <- books %>%
  filter(Rank < 20)
top_20_avg_age <- mean(bk_top_20$Ages, na.rm = TRUE)
print(paste("The top 20 books were published at age", format(top_20_avg_age, digits = 2), "on average."))
```

```{r}
# language distribution analysis
table(books$Language)

# vizualized version
viz <- ggplot(books, aes(x = Language)) +
  geom_bar(color = "pink", width = 0.7, fill = "pink") +
  geom_text(
    stat = "count",
    aes(label = after_stat(count)),
    position = position_stack(vjust = 0.5),
    size = 3,
    color = "black"
  ) +
  coord_flip() +
  labs(
    x = "Language",
    y = "Number of Books",
    title = "Top 100 Books",
    subtitle = "Language Distribution"
  ) +
  theme_minimal(base_size = 13) +
  theme(
    plot.title = element_text(face = "bold", size = 15),
    plot.subtitle = element_text(size = 12, color = "gray40"),
    axis.text.y = element_text(face = "bold")
  )
viz
```
```{r}
# try a histogram for author's ages w measures of central tendences median and mean
hist <- qplot(books$Ages,
      geom='histogram',
      binwidth = 3,  
      main = 'Age of Top 100 Novel Authors at Publication', 
      xlab = 'Publication Age',
      ylab = 'Count',
      fill=I("blue"), 
      col=I("red"), 
      alpha=I(.2)
    ) +
  geom_vline(aes(xintercept=median(books$Ages),
                 color="median"), 
                 linetype="dashed",
                 size=1
    ) +
  geom_vline(aes(xintercept=mean(books$Ages),
                 color="mean"), 
                 linetype="solid",
                 size=1
    ) +
  scale_color_manual(name = "statistics", values = c(median = "blue", mean = "red")
    )
hist
```